# Workflow that runs on every pull request.  It builds the code and runs unit tests.
name: CI - Build and Test

on:
  pull_request:
    branches:
      - '**'
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 24.x
        uses: actions/setup-node@v4
        with:
          node-version: '24.x'
          registry-url: 'https://registry.npmjs.org/'

      - name: Install PowerShell
        uses: PSModule/Install-PowerShell@v1

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Run unit tests
        run: npm test
